### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by dianeo** [awsdocs/amazon-api-gateway-developer-guide#10]
If you have ideas about any areas of confusion that I should address in our Amazon API Gateway Developer Guide, please let me know!

Submit a pull request as explained in these directions: https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/CONTRIBUTING.md .

I look forward to hearing from you.

**Comment by tbriot** [comment]
Hi Diane,
- a part that is confusing to me is how to **invoke a Private API**, when you unticked **Enabled Private DNS Name** while creating the VPC Endpoint.
I understand that you have to point to the VPC Endpoint DNS and pass the API DNS in the http Host header. But I don't feel this is clear in the doc. There is only a  cURL command example.

- when you choose to tick **Enabled Private DNS Name** while creating the VPC Endpoint, then all calls originating from your VPC to an Amazon API Gateway endpoint in the region will go through the VPC endpoint. **Including public API**. Those calls to public APIs will fail, because they cannot be invoked by a VPC endpoint. I think it deserves a note in the documentation.

**Comment by dianeo** [comment]
Sorry for the slow response. I'm adding this to the API Gateway doc backlog so it will be addressed soon.
