### ISSUE TITLE
prefix http://, https:// required for issuer in jwt-authorizer?

### ISSUE THREAD

**Issue by devdavidkarlsson** [awsdocs/amazon-api-gateway-developer-guide#79]
the issuer in the tokens from google [and a lot of other providers] is on the format: "accounts.google.com"

but it seems the jwt-authorizer config requires an issuer url with "https://" in front

That means the google tokens never be accepted by the authorizer since the token iss claim is missing: https

Is this assumption correct? I am hoping that the documentation is missing that gives the authorizer slack on this so it can be configured to work.

**Comment by jasonmac01** [comment]
Interesting, because the OIDC specification calls out [https specifically](https://openid.net/specs/openid-connect-core-1_0.html#IDToken). 

We do try to remain compliant with OAuth2 as well as a subset of OIDC. The OAuth2 specification makes no mention of the formatting of an access token.

Can you give a bit more detail here on reproducing the issue? Specifically, how are you generating your tokens? Perhaps an example, masked snippet would be useful as well that includes the iss claim (feel free to DM that to me privately if you'd like).

**Comment by devdavidkarlsson** [comment]
Interesting, I can see that you are right. Maybe the client we are using is misconfigured on google 
or something.

Edit: It appears the webservice was using a legacy google api for getting tokens.

Appreciate the swift response! 👍
